### ISSUE TITLE
GPU memory keeps increasing while using reverb

### ISSUE THREAD

**Issue by ChenYang-ChenYang** [speechbrain/speechbrain#1036]
Hi,

I try to train templates/speech_recognition/ASR/train.py with full librispeech dataset, set the following vaule in train.yaml:
reverb_prob:1.0 (in the env_corrupt part)
sorting:descending (use long data first to avoid memory increasing by data size increasing)
batch_size:2
In order to reduce memory use, I use the wavs_noise only in prepare_features() in train.py, instead of concatnating original and augmented data in a batch.
The GPU memory keeps increasing till OOM.

Env information:
Pytorch 1.9
GPU: GeForce RTX 2080, 11G

I did some researches:
1. The following use_fft parameter is True in speechbrain.processing.signal_processing.py by default. The the memory will be stable and work well if setting it to False.
  waveforms = convolve1d(
        waveform=waveforms,
        kernel=rir_waveform,
        use_fft=False,
        rotation_index=direct_index,
    )

2. If setting reverb_prob:0.0 to disable reverb, the memory will be stable and work well.
3. If using mini-librispeech data to train with reverb_prob:1.0, the memory will be stable and work well after I train serveral epochs.
4. If I change prepare_features() to concatnate original and augmented data in a batch, and set use_fft=True in convolve1d(), it will report size not match error:
File ".../speechbrain/core.py", line 853, in fit_batch
    outputs = self.compute_forward(batch, Stage.TRAIN)
  File "train.py", line 81, in compute_forward
    feats, self.feat_lens = self.prepare_features(stage, batch.sig)
  File "train.py", line 144, in prepare_features
    wavs = torch.cat([wavs, wavs_noise], dim=0)
RuntimeError: Sizes of tensors must match except in dimension 1. Got 1761 and 17760 (The offending index is 0)

As a summary, there are two issues: 
1. Reverb using FFT will cause memory leak, but works well with torch.nn.functional.conv1d
2. If using torch.nn.functional.conv1d, the returned dimension does not match original wav dimension. 

Could anyone help to have a look?

Thanks
Chen Yang

**Comment by ChenYang-ChenYang** [comment]
> Hi, I will let @mravanelli look into that. However, from what I see, use_fft is set to False by default as it is prefered when using CPUs. But we might have a problem when it is set to True. as this is something we commonly don't use :/ Thanks for pointing this out.

Yes, correct my inaccurate description. use_fft is set to False by default in convolve1d() in signal_processing.py. It is set to True in reverberate().

**Comment by mravanelli** [comment]
Hi @ChenYang-ChenYang, thank you for reporting that! 

1. As far as I recall, we did not observe any memory leak when adding reverberation. I inspected the code [here](https://github.com/speechbrain/speechbrain/blob/develop/speechbrain/processing/signal_processing.py#L225) and I cannot easily identify any potential source of memory leakage. Does it happen even if you add `.detach()` right after calling the environmental corruption model?  @pplantinga could you please double check it?
2. As for your point 4, this is essentially what is done [here](https://github.com/speechbrain/speechbrain/blob/develop/templates/speech_recognition/ASR/train.py#L143), without causing any dimensionality issue, right?

**Comment by pplantinga** [comment]
It might be worth checking at this point whether conv1d is still slow with large kernel, its possible that torch has fixed the issue and we don't need FFT anymore.

**Comment by ChenYang-ChenYang** [comment]
Finally, we changed use_fft part as following which we used in other project before. The memory did not increase. 
    
 if use_fft:

        # Calculate the number of fft used for linear convolution
        waveform_len = waveform.size(-1)
        kernel_len = kernel.size(-1)
        conv_length = waveform_len + kernel_len
        n_fft = 1 if conv_length == 0 else 2 ** (conv_length - 1).bit_length()

        # Perform padding to ensure same length
        waveform = torch.nn.functional.pad(
            input=waveform, pad=(0, n_fft - waveform_len, 0, 0, 0, 0)
        )
        kernel = torch.nn.functional.pad(
            input=kernel, pad=(0, n_fft - kernel_len, 0, 0, 0, 0)
        )

        # Multiply in frequency domain to convolve in time domain
        if version.parse(torch.__version__) > version.parse("1.6.0"):
            import torch.fft as fft

            result = fft.rfft(waveform) * fft.rfft(kernel)
            convolved = fft.irfft(result, n=n_fft)

**Comment by Adel-Moumen** [comment]
Hello, 

This issue seems to be solved by using `use_fft`. I am therefore closing this issue. Feel free to reopen the issue if you are still facing some issues. 

Best, 
Adel
