### ISSUE TITLE
Speech Recognition template not working

### ISSUE THREAD

**Issue by stefan-falk** [speechbrain/speechbrain#1190]
### Environment

- Python: 3.9
- SpeechBrain: 0.5.10

### Description

I tried to run the [template for speech recognition](https://github.com/speechbrain/speechbrain/tree/develop/templates/speech_recognition) but unfortunately the training is crashing after a few steps:

```none
speechbrain.utils.checkpoints - Would load a checkpoint here, but none found yet.
speechbrain.utils.epoch_loop - Going into epoch 1
 55%|█████████████▏          | 208/380 [03:20<02:46,  1.03it/s, train_loss=1.02]
speechbrain.core - Exception:
Traceback (most recent call last):
  File "/home/sfalk/tmp/speech/src/ml/speech/bin/sb/train.py", line 462, in <module>
    asr_brain.fit(
  File "/home/sfalk/miniconda3/envs/speech/lib/python3.9/site-packages/speechbrain/core.py", line 1033, in fit
    loss = self.fit_batch(batch)
  File "/home/sfalk/miniconda3/envs/speech/lib/python3.9/site-packages/speechbrain/core.py", line 853, in fit_batch
    outputs = self.compute_forward(batch, Stage.TRAIN)
  File "/home/sfalk/tmp/speech/src/ml/speech/bin/sb/train.py", line 85, in compute_forward
    encoded_signal = self.modules.encoder(feats.detach())
  File "/home/sfalk/miniconda3/envs/speech/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sfalk/miniconda3/envs/speech/lib/python3.9/site-packages/speechbrain/nnet/containers.py", line 144, in forward
    x = layer(x)
  File "/home/sfalk/miniconda3/envs/speech/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sfalk/miniconda3/envs/speech/lib/python3.9/site-packages/speechbrain/nnet/RNN.py", line 271, in forward
    output, hn = self.rnn(x)
  File "/home/sfalk/miniconda3/envs/speech/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sfalk/miniconda3/envs/speech/lib/python3.9/site-packages/torch/nn/modules/rnn.py", line 691, in forward
    result = _VF.lstm(input, hx, self._flat_weights, self.bias, self.num_layers,
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
```

Any idea what is causing this issue?

**Comment by stefan-falk** [comment]
@TParcollet Hi! Thanks for replying! I've already reduced it to 4 but I can try to go down further. I'm running this on 4x GeForce 1080 Ti (11 GB VRAM each). How can activate dynamic batching here and what exactly does it do?

**Comment by TParcollet** [comment]
So dynamic batching still is under PR (see the pull request list) but is about to be merged, you can either wait or directly checkout the corresponding branch. Are you using DP or DDP ? If it's DDP going down to 2 per GPU totally is fine to me, it remains a batch size of 8 which is already good for training.

**Comment by stefan-falk** [comment]
Sorry, what does DP/DDP stand for? 

I've followed your advice and tuned it down to a batch-size of just 1. The training seems to work now 👍. The next step for me here would be to write a simple Android MVP in order to execute the model on a mobile device.

After that I will revisit the training itself and change the code s.t. I can use my own data.

**Comment by Adel-Moumen** [comment]
Hello @stefan-falk, 

DP = Data Parallelism ; DDP = Distributed Data Parallelism. 

You can read further on that topic directly here: https://pytorch.org/tutorials/intermediate/ddp_tutorial.html and https://pytorch.org/docs/stable/generated/torch.nn.DataParallel.html 

I'm closing this issue as it seems to be solved. 

Please feel free to reopen if you have further questions. 😃
