### ISSUE TITLE
[Bug]: Training TTS LJSpeech on WSL2 CUDA

### ISSUE THREAD

**Issue by eix128** [speechbrain/speechbrain#1948]
### Describe the bug

Hi , i have windows pc.
I wanted to train script but it shows me out of memory error but my pc has 16GB RTX 3080 card and no other application is using the GPU.
Only i tried to run script on WSL2 


root@DESKTOP-1FOMMFD: /speechbrain/recipes/LJSpeech/TTS/tacotron2# python3 train.py --
device=cuda:0 --max_grad_norm=1.0 --data_folder=LJSpeech-1.1 hparams/train.yaml
speechbrain.core - Beginning experiment!
speechbrain.core - Experiment folder: ./results/tacotron2/1234
ljspeech_prepare - Skipping preparation, completed in previous run.
speechbrain.core - 28.2M trainable parameters in Tacotron2Brain
speechbrain.utils.checkpoints - Would load a checkpoint here, but none found yet.
speechbrain.utils.epoch_loop - Going into epoch 1
  0%|                                                                                                                                                                                                         | 0/184 [00:00<?, ?it/s]/usr/local/lib/python3.10/dist-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3483.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
  1%|█▉                                                                                                                                                                              | 2/184 [00:11<18:09,  5.99s/it, train_loss=39.8]
speechbrain.core - Exception:
Traceback (most recent call last):
  File "/root/speechbrain/recipes/LJSpeech/TTS/tacotron2/train.py", line 387, in <module>
    tacotron2_brain.fit(
  File "/usr/local/lib/python3.10/dist-packages/speechbrain-0.5.14-py3.10.egg/speechbrain/core.py", line 1233, in fit
    self._fit_train(train_set=train_set, epoch=epoch, enable=enable)
  File "/usr/local/lib/python3.10/dist-packages/speechbrain-0.5.14-py3.10.egg/speechbrain/core.py", line 1086, in _fit_train
    loss = self.fit_batch(batch)
  File "/root/speechbrain/recipes/LJSpeech/TTS/tacotron2/train.py", line 78, in fit_batch
    result = super().fit_batch(batch)
  File "/usr/local/lib/python3.10/dist-packages/speechbrain-0.5.14-py3.10.egg/speechbrain/core.py", line 958, in fit_batch
    (loss / self.grad_accumulation_factor).backward()
  File "/usr/local/lib/python3.10/dist-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 108.00 MiB (GPU 0; 16.00 GiB total capacity; 15.02 GiB already allocated; 0 bytes free; 15.23 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
root@DESKTOP-1FOMMFD:~/speechbrain/recipes/LJSpeech/TTS/tacotron2#








Nvidia SMi gives me all memory is free nearly:
     0MiB / 16384MiB

root@DESKTOP-1FOMMFD:~/speechbrain/recipes/LJSpeech/TTS/tacotron2# nvidia-smi
Wed Apr 19 15:22:18 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 531.14       CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3080 L...    On | 00000000:01:00.0 Off |                  N/A |
| N/A   46C    P8               11W /  N/A|      0MiB / 16384MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A        22      G   /Xwayland                                 N/A      |
+---------------------------------------------------------------------------------------+

### Expected behaviour

The training of tacotron2 should run.

### To Reproduce

echo WSL2 Windows with CUDA support RTX 3080 16GB Card 
wget http://data.keithito.com/data/speech/LJSpeech-1.1.tar.bz2
tar -xf LJSpeech-1.1.tar.bz2
rm LJSpeech-1.1.tar.bz2
cd /root/speechbrain/recipes/LJSpeech/TTS/tacotron2
python3 train.py --device=cuda:0 --max_grad_norm=1.0 --data_folder=LJSpeech-1.1 hparams/train.yaml

### Versions

latest release SpeechBrain 

### Relevant log output

```shell
speechbrain.utils.epoch_loop - Going into epoch 1
  0%|                                                                                                                                                                                                         | 0/184 [00:00<?, ?it/s]/usr/local/lib/python3.10/dist-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3483.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
  1%|█▉                                                                                                                                                                              | 2/184 [00:11<18:09,  5.99s/it, train_loss=39.8]
speechbrain.core - Exception:
Traceback (most recent call last):
  File "/root/speechbrain/recipes/LJSpeech/TTS/tacotron2/train.py", line 387, in <module>
    tacotron2_brain.fit(
  File "/usr/local/lib/python3.10/dist-packages/speechbrain-0.5.14-py3.10.egg/speechbrain/core.py", line 1233, in fit
    self._fit_train(train_set=train_set, epoch=epoch, enable=enable)
  File "/usr/local/lib/python3.10/dist-packages/speechbrain-0.5.14-py3.10.egg/speechbrain/core.py", line 1086, in _fit_train
    loss = self.fit_batch(batch)
  File "/root/speechbrain/recipes/LJSpeech/TTS/tacotron2/train.py", line 78, in fit_batch
    result = super().fit_batch(batch)
  File "/usr/local/lib/python3.10/dist-packages/speechbrain-0.5.14-py3.10.egg/speechbrain/core.py", line 958, in fit_batch
    (loss / self.grad_accumulation_factor).backward()
  File "/usr/local/lib/python3.10/dist-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 108.00 MiB (GPU 0; 16.00 GiB total capacity; 15.02 GiB already allocated; 0 bytes free; 15.23 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```


### Additional context
WSL2 CUDA Installation steps on Ubuntu 22.04

wget https://developer.download.nvidia.com/compute/cuda/repos/wsl-ubuntu/x86_64/cuda-wsl-ubuntu.pin
sudo mv cuda-wsl-ubuntu.pin /etc/apt/preferences.d/cuda-repository-pin-600
wget https://developer.download.nvidia.com/compute/cuda/11.8.0/local_installers/cuda-repo-wsl-ubuntu-11-8-local_11.8.0-1_amd64.deb
sudo mv cuda-wsl-ubuntu.pin /etc/apt/preferences.d/cuda-repository-pin-600
sudo dpkg -i cuda-repo-wsl-ubuntu-11-8-local_11.8.0-1_amd64.deb
sudo cp /var/cuda-repo-wsl-ubuntu-11-8-local/cuda-9EA88183-keyring.gpg /usr/share/keyrings/
sudo dpkg -i cuda-repo-wsl-ubuntu-11-8-local_11.8.0-1_amd64.deb
sudo apt-get update
nvidia-smi
sudo apt-get install cuda
nvidia-smi
apt install python3
apt install python3-pip
pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu118
echo -e "[user]\ndefault=root" > /etc/wsl.conf
cat /etc/wsl.conf

**Comment by AsuMagic** [comment]
I think you are assuming that PyTorch fails to allocate any memory at all, but the error merely means it failed to allocate GPU memory _after_ allocating a bunch.

Try reducing the `batch_size` in the `hparams.yaml`, e.g. from 64 to something much smaller (e.g. 8 or 16), and if it works, dial it back up a bit to regain some performance. The README seems to hint that whoever configured the recipe configured it for a RTX8000, which is a 48GB card. That would explain why the default batch size does not fit your GPU.

**Comment by eix128** [comment]
Thanks the problem solved now.
But why gpu usage is low on training.
I would expect ~%80 gpu usage but on taskmanager shows no gpu usage.
Well but on 
WSL linux i see   94% with nvidia-smi.

Thanks for help

**Comment by AsuMagic** [comment]
> I would expect ~%80 gpu usage but on taskmanager shows no gpu usage.

I don't think that's surprising. The task manager probably fails to track it, whether that's because of virtualization of because of it being a CUDA workload rather than a 3D API. Either way it's not a concern if it training is working properly.

I'm assuming the problem is resolved so I will close the issue, feel free to reopen if that isn't the case.
