### ISSUE TITLE
RunOpts no longer working with DDP (single and multinode)

### ISSUE THREAD

**Issue by helleuch** [speechbrain/speechbrain#2950]
### Describe the bug

I had to checkout to this commit to bypass the issue: ` ba9364af76f95683348f83b211c90b4301788734 `

Since the RunOpts dataclass refactor, my scripts are no longer working on the HPC cluster Jean-Zay.
The `distributed_backend` attribute is always set to `None`. The expected behaviour is to for it to be automatically set to `nccl`.

I tried the following: 
1. Setting it manually to `nccl` via arg prams or in the code: The train starts until the train log prints, then a deadlock happens and the NCCL watchdog stops the processes.
2. Re-creating a `run_opts` object in the train script, and loading the hparams after:  it is then impossible to run this: 
```python
with open(hparams_file, encoding="utf-8") as fin:
        hparams = load_hyperpyyaml(fin, overrides)
    hparams.update(run_opts) # => Throws error: "Could not update hprams from run_opts: attribute name must be string, not 'int'"
```

I was using the latest commit as of the 17/08/2025.

I tested multiple scripts from different projects of mine. Furthermore, I tested both single-node and multi-node DDP.

Here's an example of the error I get when trying to fine-tune Whisper for an ASR task using 4 GPUs on the same node: 
```log
Traceback (most recent call last):
  File "<my_path>/model/train_whisper.py", line 275, in <module>
    sb.utils.distributed.ddp_init_group(run_opts)
  File "<hidden>/speechbrain/speechbrain/utils/distributed.py", line 323, in ddp_init_group
Traceback (most recent call last):
  File "<hidden>/model/train_whisper.py", line 275, in <module>
    run_opts["distributed_backend"]
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

Could it be that I need to change the way I run my scripts and not an error ?  I currently run my scripts like follows:
```bash
<SLURM config stuff>
<Loading relevant modules>
conda activate <env>
cd <train_script_path>
torchrun --nproc_per_node=4 \
        --nnodes=${SLURM_JOB_NUM_NODES} \
        --node_rank=${SLURM_NODEID} \
        --rdzv_id=12345 \
        --rdzv_backend=c10d \
        --rdzv_endpoint=$RDZV_ENDPOINT \
        --rdzv_conf="timeout=600" \
        train_whisper.py hparams/whisper.yaml
```

Thank you for your help and your work on Speechbrain ! :D

### Expected behaviour

For the training to.art as it previously did.

### To Reproduce

Use multiple GPUs:
```bash
torchrun --nproc_per_node=4 \
        --nnodes=${SLURM_JOB_NUM_NODES} \
        --node_rank=${SLURM_NODEID} \
        --rdzv_id=12345 \
        --rdzv_backend=c10d \
        --rdzv_endpoint=$RDZV_ENDPOINT \
        --rdzv_conf="timeout=600" \
        train_whisper.py hparams/whisper.yaml
```

### Environment Details

Speechbrain installed from source.
Python version: 3.11
Using the last commit as of 17/08/2025

### Relevant Log Output

```shell
Traceback (most recent call last):
  File "/path/to/your/project/model/train_whisper.py", line 275, in <module>
    sb.utils.distributed.ddp_init_group(run_opts)
  File "/path/to/speechbrain/speechbrain/utils/distributed.py", line 323, in ddp_init_group
Traceback (most recent call last):
  File "/path/to/your/project/model/train_whisper.py", line 275, in <module>
    run_opts["distributed_backend"]
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

### Additional Context

Used to work fine before updating my Speechbrain repo.
A checkout to this commit to "solves" the issue: ba9364af76f95683348f83b211c90b4301788734

**Comment by pplantinga** [comment]
Thanks for reporting this, definitely a bug!

If you have some time, would you be able to test the proposed fix in #2952 to ensure it works for your setup?

**Comment by helleuch** [comment]
Hello,
Thank you for your help. I will try it on my setup and let you know how it goes.

**Comment by helleuch** [comment]
Hello again,
It seems there are still some errors: 
```bash
[rank0]: Traceback (most recent call last):
[rank0]:   File ".../train_hybrid.py", line 400, in <module>
[rank0]:     main()
[rank0]:   File ".../train_hybrid.py", line 340, in main
[rank0]:     hparams.update(run_opts)  # => Throws errors: int key
[rank0]:     ^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../speechbrain/speechbrain/utils/run_opts.py", line 211, in __getitem__
[rank0]:     return getattr(self, key)
[rank0]:            ^^^^^^^^^^^^^^^^^^
[rank0]: TypeError: attribute name must be string, not 'int'
```

**Comment by pplantinga** [comment]
It looks like you are trying to add all of the `run_opts` to the `hparams`. We refactored the `run_opts` so it is no longer a dictionary but a dataclass, but it can easily be converted back to a dictionary with `run_opts = run_opts.as_dict()`. Could you try adding this line before adding the `run_opts` to the `hparams`?

**Comment by pplantinga** [comment]
Or convert the line to `hparams.update(run_opts.as_dict())`

**Comment by helleuch** [comment]
I updated that line and the hparams update is now fixed (sorry for the oversight)

However, the deadlock still happens. Here's how it looks like in my log file: 
```bash
  1%|          | 94/14199 [01:20<1:58:47,  1.98speechbrain.utils.train_logger - steps: 100, lr: 3.20e-06, avg_loss: 7.65
```
Of course, the `tqdm` bar is supposed to continue in a line below after the step_logger update, but it just freezes.

**Comment by pplantinga** [comment]
I don't think we have enough info to diagnose the deadlock here, it might not necessarily be related to the RunOptions. In order for it to deadlock at least one of the processes must have run into some kind of error or severe slowdown, and I'm not sure why RunOptions would have caused this unless the command line is somehow formatted wrongly on some processes but not others?

One thing that might help is to try and find the commit that causes the deadlock. Is `ba9364af76f95683348f83b211c90b4301788734` the latest commit for which the deadlock doesn't occur?

**Comment by helleuch** [comment]
It is ineed. I simply kept rolling back until my scripts worked again.

**Comment by pplantinga** [comment]
If the error is consistent, then that would make this the offending commit, but this seems unlikely as it only affects the test.

https://github.com/speechbrain/speechbrain/commit/0ff5c0c8f5f3efe18d70b41e4572879575523fca

Maybe the error is happening intermittently. If it is indeed a new error, it could potentially be related to the new sync added for GlobalNorm in 9e068c4ef065aea1f9e9858f92d5c0052766f6af? At any rate, perhaps it is better to open a new issue here with as much info as you can provide about the deadlock, as the original issue is fixed by #2952

**Comment by helleuch** [comment]
Thank you. I will do that as soon as I have the time.

**Comment by whettenr** [comment]
Im getting a similar issue. I think some of the recent changes have affected DDP. Here I print out the run_opts and the error I get.

```
W0728 12:47:16.232000 1443 site-packages/torch/distributed/run.py:792] 
W0728 12:47:16.232000 1443 site-packages/torch/distributed/run.py:792] *****************************************
W0728 12:47:16.232000 1443 site-packages/torch/distributed/run.py:792] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0728 12:47:16.232000 1443 site-packages/torch/distributed/run.py:792] *****************************************
RunOptions(test_only=False, debug=False, debug_batches=None, debug_epochs=None, debug_persistently=False, device=None, data_parallel_backend=False, data_parallel_count=-1, distributed_backend=None, distributed_launch=False, find_unused_parameters=True, jit=False, jit_module_keys=None, compile=False, compile_module_keys=None, compile_mode=None, compile_using_fullgraph=False, compile_using_dynamic_shape_tracing=False, precision=None, eval_precision=None, auto_mix_prec=False, bfloat16_mix_prec=False, max_grad_norm=None, skip_nonfinite_grads=False, nonfinite_patience=None, noprogressbar=False, ckpt_interval_minutes=None, ckpt_interval_steps=None, grad_accumulation_factor=8, optimizer_step_limit='150000', tqdm_colored_bar=False, tqdm_barcolor={'train': 'GREEN', 'valid': 'MAGENTA', 'test': 'CYAN'}, remove_vector_weight_decay=False, profile_training=False, profile_warmup=None, profile_steps=None, log_config=None, param_file='hparams/lebench_BEST-RQ.yaml', overridden_args={'optimizer_step_limit', 'find_unused_parameters', 'grad_accumulation_factor'})
RunOptions(test_only=False, debug=False, debug_batches=None, debug_epochs=None, debug_persistently=False, device=None, data_parallel_backend=False, data_parallel_count=-1, distributed_backend=None, distributed_launch=False, find_unused_parameters=True, jit=False, jit_module_keys=None, compile=False, compile_module_keys=None, compile_mode=None, compile_using_fullgraph=False, compile_using_dynamic_shape_tracing=False, precision=None, eval_precision=None, auto_mix_prec=False, bfloat16_mix_prec=False, max_grad_norm=None, skip_nonfinite_grads=False, nonfinite_patience=None, noprogressbar=False, ckpt_interval_minutes=None, ckpt_interval_steps=None, grad_accumulation_factor=8, optimizer_step_limit='150000', tqdm_colored_bar=False, tqdm_barcolor={'train': 'GREEN', 'valid': 'MAGENTA', 'test': 'CYAN'}, remove_vector_weight_decay=False, profile_training=False, profile_warmup=None, profile_steps=None, log_config=None, param_file='hparams/lebench_BEST-RQ.yaml', overridden_args={'optimizer_step_limit', 'grad_accumulation_factor', 'find_unused_parameters'})
Traceback (most recent call last):
  File "/local_disk/apollon/rwhetten/sss_data_selection/training/lebench_train.py", line 360, in <module>
    main()
  File "/local_disk/apollon/rwhetten/sss_data_selection/training/lebench_train.py", line 312, in main
    sb.utils.distributed.ddp_init_group(run_opts)
  File "/data/coros3/rwhetten/attention_alt/speechbrain/speechbrain/utils/distributed.py", line 323, in ddp_init_group
Traceback (most recent call last):
  File "/local_disk/apollon/rwhetten/sss_data_selection/training/lebench_train.py", line 360, in <module>
    main()
  File "/local_disk/apollon/rwhetten/sss_data_selection/training/lebench_train.py", line 312, in main
    sb.utils.distributed.ddp_init_group(run_opts)
  File "/data/coros3/rwhetten/attention_alt/speechbrain/speechbrain/utils/distributed.py", line 323, in ddp_init_group
    run_opts["distributed_backend"]
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
    run_opts["distributed_backend"]
```

**Comment by pplantinga** [comment]
I have just merged the fix for this issue. Please give it a try and let me know if it now works for you.

**Comment by Nivedita5** [comment]
Hi. I am running into a similar issue. With the earlier version, DDP was running fine, but with the latest commits, distributed processing is not possible.

**Comment by whettenr** [comment]
i tried doing this:
`hparams.update(run_opts.as_dict())`
but then got another error. Basically I think one or more of the hyperparameters got converted to a string and then the computer was having and issue with the `>` operation because it was trying to compare a sting to an integer.

**Comment by pplantinga** [comment]
> Hi. I am running into a similar issue. With the earlier version, DDP was running fine, but with the latest commits, distributed processing is not possible.

Are you using the latest develop? The above issue should be fixed. If it is not, please open a new issue.
