### ISSUE TITLE
CUBLAS_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by gandolfxu** [speechbrain/speechbrain#581]
Traceback (most recent call last):
  File "train_embeddings.py", line 229, in <module>
    valid_loader_kwargs=hparams["dataloader_options"],
  File "/home/*/Software/speechbrain/lib/python3.7/site-packages/speechbrain/core.py", line 1009, in fit
    loss = self.fit_batch(batch)
  File "/home/*/Software/speechbrain/lib/python3.7/site-packages/speechbrain/core.py", line 835, in fit_batch
    outputs = self.compute_forward(batch, Stage.TRAIN)
  File "train_embeddings.py", line 65, in compute_forward
    feats = self.modules.compute_features(wavs)
  File "/home/*/Software/speechbrain/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/*/Software/speechbrain/lib/python3.7/site-packages/speechbrain/lobes/features.py", line 119, in forward
    fbanks = self.compute_fbanks(mag)
  File "/home/*/Software/speechbrain/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/*/Software/speechbrain/lib/python3.7/site-packages/speechbrain/processing/features.py", line 545, in forward
    fbanks = torch.matmul(spectrogram, fbank_matrix)
RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasCreate(handle)`

I have print out shape of spectrogram and fbank_matrix:
torch.Size([2, 301, 201]) torch.Size([201, 80])

GPU：GeForce RTX 2080 Ti ，Memory：11019MiB

**Comment by TParcollet** [comment]
Hi,

It is most likely a CUDA OOM issue. Please monitor your GPU VRAM usage with nvidia-smi while this happens.

**Comment by TParcollet** [comment]
Is it solved ?

**Comment by alpoktem** [comment]
I was able to fix this by reverting back to torch 1.7.1 
https://pytorch.org/get-started/previous-versions/
