### ISSUE TITLE
train LibriSpeech ASR acoustic model with ["train-clean-100"], error happens

### ISSUE THREAD

**Issue by yujunlhz** [speechbrain/speechbrain#764]
hey:
When I train train LibriSpeech ASR acoustic model with ["train-clean-100"],  (not the total 960h), error happens, what might be the culprit?  Thanks

speechbrain/recipes/LibriSpeech/ASR/seq2seq# python train.py hparams/train_BPE_1000.yaml &

Skipping download
speechbrain.core - Beginning experiment!
speechbrain.core - Experiment folder: results/CRDNN_BPE_960h_LM/2602
speechbrain.pretrained.fetching - Fetch lm.ckpt: Using existing file/symlink in results/CRDNN_BPE_960h_LM/2602/save/lm.ckpt.
speechbrain.pretrained.fetching - Fetch tokenizer.ckpt: Using existing file/symlink in results/CRDNN_BPE_960h_LM/2602/save/tokenizer.ckpt.
speechbrain.utils.parameter_transfer - Loading pretrained files for: lm, tokenizer
speechbrain.core - Info: ckpt_interval_minutes arg from hparam file is used
speechbrain.core - 173.0M trainable parameters in ASR
speechbrain.utils.checkpoints - Would load a checkpoint here, but none found yet.
speechbrain.utils.epoch_loop - Going into epoch 1
 25%|█████▌                | 902/3568 [09:52<29:11,  1.52it/s, train_loss=6.14]
speechbrain.core - Exception:
Traceback (most recent call last):
  File "train.py", line 357, in <module>
    asr_brain.fit(
  File "/tmp/lingvo/speechbrain/speechbrain/core.py", line 1013, in fit
    loss = self.fit_batch(batch)
  File "train.py", line 162, in fit_batch
    loss.backward()
  File "/usr/local/lib/python3.8/dist-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/__init__.py", line 145, in backward
    Variable._execution_engine.run_backward(
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

I am using torch==1.8.1+cu102

**Comment by qmeeus** [comment]
This script works fine for me, maybe you don't have a GPU with enough memory? Have you tried decreasing the batch size?

**Comment by TParcollet** [comment]
It indeed is a memory issue.

**Comment by yujunlhz** [comment]
Thanks.  when I change the batch_size to 4, the issue is gone.

it looks like the memory usage fluctuates with the length of utterances.  what is the longest the utterance in second is allow for the ASR training?

**Comment by TParcollet** [comment]
There is no limit to the LibriSpeech recipe. You can have a look at the CommonVoice recipes if you want to see how to limit the size of audio files. It is done with the avoid_if_longer_than + dynamic transformer on the DynamicDataset :)
