### ISSUE TITLE
Transducer loss leads to memory leak

### ISSUE THREAD

**Issue by YangHao97** [speechbrain/speechbrain#895]
Hi, I'm using your transducer loss codes and pytorch-lightning to train my model. But I found the 4D tensor which is used to calculate transducer will be accumulated in GPU, when I check the GPU memory in training step(before a batch starts), there are many 4D tensor(come from the previous batches) in the GPU memory. That will lead to CUDA out of memory finally. I don't know what went wrong.
![1627270736(1)](https://user-images.githubusercontent.com/71253402/126929906-e169f6d1-8c83-4df0-be18-ccc3d244b5d8.png)
gpu_tracker is used to check the GPU memory.
![1627270828(1)](https://user-images.githubusercontent.com/71253402/126930012-db76a659-a162-430d-a195-256a19ceb3ee.png)
The loss in training step is from this.
![1627270920(1)](https://user-images.githubusercontent.com/71253402/126930114-3a65f445-32e5-4fbe-b579-a6b7cddc96a3.png)
This is the result of GPU memory usage in training step.
I try to use 'del', 'gc.collect()' and 'torch.cuda.empty_cache()' in everywhere, but they are all useless.

**Comment by TParcollet** [comment]
Torch should soon support natively the transducer loss and we will switch to it. However, this behavior shouldn't be expected. Are you sure that the increase in memory isn't due to sorting: ascending in your config file ?

**Comment by YangHao97** [comment]
Hi @TParcollet , thanks for your reply.
I have changed the codes in figure 1 to the codes in figure 2, and it works. I'm not sure if different versions of pytorch, lightning and so on lead to this problem.
![image](https://user-images.githubusercontent.com/71253402/127378336-02ed27d8-6824-41e4-8330-76f223862569.png)
figure 1
![image](https://user-images.githubusercontent.com/71253402/127378358-24794616-94cb-49c3-b3b2-32f29e83979d.png)
figure 2

**Comment by mravanelli** [comment]
Any insight here @aheba?

**Comment by TParcollet** [comment]
@YangHao97 did you see any speed degradation with your new code/ ?

**Comment by Gastron** [comment]
Closing due to lack of activity here, but reopen if there's followups.
